'reinit'
'open F:\data\gs\cal1w.ctl'
'enable print F:\data\winter.gmf'
'set gxout shaded'
'set cmax 5'
'set cint 0.2'
'd subtraction'
'set gxout contour'
'set cmax 5'
'set cint 0.2'
'd subtraction'
'print'
'disable print'


